### ISSUE TITLE
`cat` alias breaks `async` function

### ISSUE THREAD

**Issue by dvogt23** [agkozak/agkozak-zsh-prompt#19]
my `cat` alias breaks the `async` function. in changelog from dec 2018 says that `cat` is no longer used 🤔 is that cause the async job calls `cat`?

could someone help?

**Comment by agkozak** [comment]
The [change a few months ago](https://github.com/agkozak/agkozak-zsh-prompt/commit/dd0eebb95ba8c58e91fa134dfcf369992399cba9) simply makes it so that native ZSH functions are used to fetch the contents of a temporary file, rather than the external `cat` program; this makes things slightly faster. It is unlikely that this is your problem.

I'd like to try to help you, though. Are you receiving an error message? If so, what is it?

How are you defining your `cat` alias? What code does that?

Which operating system are you using?

Could you run the following two commands for me and give me the output?

    uname -a
    print $AGKOZAK_ASYNC_METHOD

Thanks!

**Comment by agkozak** [comment]
My suspicion is that whatever system you're on is defaulting to the `zsh-async` method (most likely WSL on Windows or Solaris). `zsh-async` does use `cat`, and it has an `async` function.

For the most part, it's unwise to alias basic POSIX utilities like `cat`; it causes no end of problems.

**Comment by dvogt23** [comment]
Thanks for the quick reply. Im on debain (WSL) on windows and use `zsh-async`.  I alias the `cat` command with `alias cat=bat`. The error is, that i have a lot of `zsh` & `bat` processes on the machine.

You are right, on my arch with the same env looks everything fine.

So, i have to use another async method?

**Comment by agkozak** [comment]
My main advice would be never to alias `cat` to anything else; it's the Unix command for displaying the contents of a file, and you'll find that it gets used for all sort of purposes in scripts.

That said, if you put

    AGKOZAK_FORCE_ASYNC_METHOD=usr1

in your `.zshrc` (before you load the agkozak-zsh-prompt), my prompt won't be using `cat` at all so the conflict will not occur with it.

**Comment by dvogt23** [comment]
> My main advice would be never to alias `cat` to anything else; it's the Unix command for displaying the contents of a file, and you'll find that it gets used for all sort of purposes in scripts.
> 
> That said, if you put
> 
> ```
> AGKOZAK_FORCE_ASYNC_METHOD=usr1
> ```
> 
> in your `.zshrc` (before you load the agkozak-zsh-prompt), my prompt won't be using `cat` at all, so the conflict will not occur with it.

thats helps. thanks.

Every script should use an own environment, indepent from my personal aliases, sorry. I have also have an alias for ls and so on. Never got problems with it.

**Comment by agkozak** [comment]
Scripts that you execute like programs do have their own environments. Prompts, however, are sourced into your interactive environment, so they run the risk of conflicting with everything else you do. For example, if you look at my source code, you'll see that I use variable names like `$AGKOZAK_ASYNC_METHOD` rather than `$ASYNC_METHOD`, just in case some other script gets sourced that has its own "async method."

You're right, though -- it is pretty normal to use an alias for `ls`. I do it, too, and it's a practice encouraged by lots of skeleton dotfiles provided on lots of systems. If I were writing a sourced script that used `ls`, I'd probably want to invoke it with `command ls` or `env ls` to avoid the possibility of running someone's `ls` alias. The `zsh-async` developer hasn't done that with `cat`, most likely because it's not a conflict he's run across often.

Anyway, I'm glad we've got you up and running!

**Comment by dvogt23** [comment]
Thats true, prompts have no possability to use an own env, I think. For prevent an alias to being used, you could use a `\` like `\cat` for the "real" command. Maybe I should open an issue in zsh-async with this hint :thinking: 

So, thank you so much for the great prompt and for your quick help :nerd_face:
