### ISSUE TITLE
AGKOZAK_MULTILINE not simpatico with AGKOZAK_LEFT_PROMPT_ONLY

### ISSUE THREAD

**Issue by basil** [agkozak/agkozak-zsh-prompt#24]
First of all, thank you for the excellent prompt!

If I set `AGKOZAK_LEFT_PROMPT_ONLY=1` alone, the Git status is on the left side and the prompt is two lines (as expected). If I set `AGKOZAK_MULTILINE=0` alone, the Git status is on the right side and the prompt is one line (as expected). However, if I set both `AGKOZAK_LEFT_PROMPT_ONLY=1` _and_ `AGKOZAK_MULTILINE=0`, the Git status is on the left side and the prompt is two lines (which is unexpected). The behavior I expected was for the Git status to be on the left side and for the prompt to be one line. It appears that `AGKOZAK_MULTILINE=0` somehow cancels out `AGKOZAK_LEFT_PROMPT_ONLY=1`.

**Comment by agkozak** [comment]
Thanks, Basil!

I imagine the layout you're looking for is more or less what I used in my [Polyglot Prompt](https://github.com/agkozak/polyglot), which is not asynchronous. For the agkozak-zsh-prompt, I do include in my documentation [a custom prompt](https://github.com/agkozak/agkozak-zsh-prompt#ccb012100) that works that way. I will confess that the reason I haven't made it an easily achieved configuration is simply because I don't like the way it looks on a system where Git is slow (think Windows), or in a really big repo: I'm averse to the visual effect of having the asynchronous Git display force the prompt character (`%`, or whatever you prefer) over the the right.

But tastes (and computers) differ, and I agree that it would be nice to have the two options you mention work logically together.

For now, try putting this into your `.zshrc`:

```sh
AGKOZAK_CUSTOM_PROMPT='%(?..%B%F{red}(%?%)%f%b )'
AGKOZAK_CUSTOM_PROMPT+='%(!.%S%B.%B%F{green})%n%1v%(!.%b%s.%f%b) '
AGKOZAK_CUSTOM_PROMPT+='%B%F{blue}%2v%f%b'
AGKOZAK_CUSTOM_PROMPT+='%(3V.%F{yellow}%3v%f.) '
AGKOZAK_CUSTOM_PROMPT+='%(4V.:.%#) '

AGKOZAK_CUSTOM_RPROMPT=''
```

I'll try out making it work the way you describe in a branch soon, and perhaps you test it out for me. I'd love to have it be part of the next release.

Thanks for your contribution!

**Comment by basil** [comment]
Thanks for the quick reply! That workaround did the trick.

> I will confess that the reason I haven't made it an easily achieved configuration is simply because I don't like the way it looks on a system where Git is slow (think Windows), or in a really big repo: I'm averse to the visual effect of having the asynchronous Git display force the prompt character (`%`, or whatever you prefer) over the the right.

I concur. It looks janky when the prompt is first drawn in one position and then almost immediately after shifted over. But I worked around this by setting `AGKOZAK_FORCE_ASYNC_METHOD=none`.

> I'll try out making it work the way you describe in a branch soon, and perhaps you test it out for me. I'd love to have it be part of the next release.

Sure, I'd be happy to test this out.

Thanks again!

**Comment by agkozak** [comment]
Give the `simpatico` branch a pull. Comment out that custom code I gave you and just use

    AGKOZAK_LEFT_PROMPT_ONLY=1
    AGKOZAK_MULTILINE=0

See what you think.

**Comment by basil** [comment]
The `simpatico` branch works like a charm with these three settings:

```
AGKOZAK_FORCE_ASYNC_METHOD=none
AGKOZAK_LEFT_PROMPT_ONLY=1
AGKOZAK_MULTILINE=0
```

It might be worth warning the user in the documentation to set `AGKOZAK_FORCE_ASYNC_METHOD=none` whenever `AGKOZAK_LEFT_PROMPT_ONLY=1` and `AGKOZAK_MULTILINE=0` to avoid the jankiness discussed above. Or as an alternative, the routine that detects the asynchronous method could even fall back to `none` whenever `AGKOZAK_LEFT_PROMPT_ONLY=1` and `AGKOZAK_MULTILINE=0`, allowing the user to override this choice with `AGKOZAK_FORCE_ASYNC_METHOD={subst-async,zsh-async,usr1}`.

**Comment by agkozak** [comment]
A warning that the combination might not be to everyone's taste might be good, I agree. I'm hesitant to start encouraging people to turn off the asynchronicity, naturally, as I see it as the best thing about the font, but it all depends on what you're doing, right?

Thanks again so much for making the prompt better.

**Comment by basil** [comment]
> I'm hesitant to start encouraging people to turn off the asynchronicity, naturally, as I see it as the best thing about the font, but it all depends on what you're doing, right?

That's exactly right. I agree the asynchronicity is one of the most technically impressive features of the project. And for Windows users or users with very large repositories, this might be indispensable. But I use Linux with mirrored M.2 NVMe SSDs and a 16 GB in-memory filesystem cache, so all `git(1)` operations are screaming fast for me. 🙂 In my configuration asynchronicity confers no tangible performance benefit, so I'm willing to disable it in order to have a prompt that can be rendered in one pass.

**Comment by agkozak** [comment]
I figured you had a good reason.  🙂

**Comment by agkozak** [comment]
Version 3.6.0 is available on the `master` branch; you may switch over to that now. Thanks again for the great suggestion.
