### ISSUE TITLE
Any way to customize the individual colors of the custom symbols?

### ISSUE THREAD

**Issue by brandoniffert** [agkozak/agkozak-zsh-prompt#27]
Hello, looking for a way to redefine each of the `AGKOZAK_CUSTOM_SYMBOLS` but have each symbol be a different color.

Trying this setting:
```
AGKOZAK_CUSTOM_SYMBOLS=(
  '%F{yellow}▾%f%F{green}▴%f' # Diverged
  '%F{yellow}▾%f'             # Behind
  '%F{green}▴%f'              # Ahead
  '%F{green}•%f'              # Unstaged
  '%F{red}•%f'                # Deleted
  '%F{red}•%f'                # Modified
  '%F{red}•%f'                # Renamed
  '%F{yellow}•%f'             # Untracked
  '%F{red}*%f'                # Stashed
)
```

Gives me this prompt:
```
.../tmp.3iVh9A9Q (master %F{yellow}•%f)
%
```

Any way to have those color codes interpreted?

Thank you

**Comment by brandoniffert** [comment]
@agkozak Thanks for the great explanation! Works well, thanks for making this so customizable.

**Comment by yacoob** [comment]
Apologies for resurrecting this old bug, but I'd like to turn this into a feature request :) 

I wanted to turn `@` in `psvar[1]` red. Currently, in order to achieve that, I'd need to construct an entire `AGKOZAK_CUSTOM_PROMPT` by myself, based on what's the default - and then keep track of it, as it changes over the time upstream. 

Any chance for that functionality? :)

Thanks!
