### ISSUE TITLE
FR: zsh `promptinit` API support

### ISSUE THREAD

**Issue by eddyg** [agkozak/agkozak-zsh-prompt#33]
Thanks for the flexible, lightweight, easy-to-understand prompt!

Any plans to implement support for [Zsh's `promptinit` API](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Writing-Themes)?

(For ref, this was brought up in [this zsh-snap issue](https://github.com/marlonrichert/zsh-snap/issues/66#issuecomment-826119369).)

**Comment by agkozak** [comment]
Thanks for the compliment!

I'll look into it.

**Comment by agkozak** [comment]
OK, I've got the `develop` branch working with `promptinit` (with [this commit](https://github.com/agkozak/agkozak-zsh-prompt/commit/58406506674e2354f12ea06305bd0e34220804e3)); I'll merge it to `master` when I've cleaned up and tested a few things.

I've done the following so far:

- [x] Assigned `$prompt_opts`
- [x] Renamed `_agkozak_preexec` and `_agkozak_precmd` to `prompt_agkozak_preexec` and `prompt_agkozak_precmd` so that they will be disabled when the agkozak-zsh-prompt is disabled\*
- [x] provided a help function that points the user to my `README.md`, which is copious

I'll try to provide a prompt preview function when I have more time.

Thanks, @eddyg and @marlonrichert, for helping to make the prompt better.

\* @marlonrichert, don't you have a proposed patch for the current [`promptinit` API documentation](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Writing-Themes)? What we have now doesn't sufficiently explain the naming conventions necessary to make any of this work.

**Comment by marlonrichert** [comment]
@agkozak [Yes, I’m working on a `promptinit` patch](https://www.zsh.org/mla/workers/2021/msg01009.html), but it updates only a tiny part of the documentation. What questions do you need answered?

**Comment by agkozak** [comment]
The sentence

> The `precmd` and `preexec` hooks are automatically adjusted if the prompt theme changes or is disabled.

should really be something more like

> If your `precmd` and `preexec` hooks are named `prompt_`*name*`_precmd` and `prompt_`*name*`_preexec` (where *name* is the name of your theme), they will be automatically adjusted if the theme changes or is disabled.

**Comment by marlonrichert** [comment]
Yes, that part of the documentation will be improved with my patch.

**Comment by agkozak** [comment]
@eddyg @marlonrichert [Release v3.10.0](https://github.com/agkozak/agkozak-zsh-prompt/tree/v3.10.0) now has full `promptinit` compatibility. Thanks for your suggestions.
